import { ProductCategories } from "./fake-api";

export const productCategories: Array<ProductCategories> = [
    { categoryId: 1, name: 'All' },
    { categoryId: 2, name: 'Alexa Skills' },
    { categoryId: 3, name: 'Amazon Devices' },
    { categoryId: 4, name: 'Amazon Warehouse Deals' },
    { categoryId: 5, name: 'Apps &amp; Games' },
    { categoryId: 6, name: 'Audible Audiobooks' },
    { categoryId: 7, name: 'Automotive' },
    { categoryId: 8, name: 'Baby' },
    { categoryId: 9, name: 'Beauty' },
    { categoryId: 10, name: 'Books' },
    { categoryId: 11, name: 'Clothing, Shoes &amp; Jewellery' },
    { categoryId: 12, name: '&nbsp;&nbsp;&nbsp;Women' },
    { categoryId: 13, name: '&nbsp;&nbsp;&nbsp;Men' },
    { categoryId: 14, name: '&nbsp;&nbsp;&nbsp;Girls' },
    { categoryId: 15, name: '&nbsp;&nbsp;&nbsp;Boys' },
    { categoryId: 16, name: '&nbsp;&nbsp;&nbsp;Baby' },
    { categoryId: 17, name: 'Electronics' },
    { categoryId: 18, name: 'Gift Cards' },
    { categoryId: 19, name: 'Grocery' },
    { categoryId: 20, name: 'Handmade' },
    { categoryId: 21, name: 'Health &amp; Personal Care' },
    { categoryId: 22, name: 'Home &amp; Kitchen' },
    { categoryId: 23, name: 'Industrial &amp; Scientific' },
    { categoryId: 24, name: 'Kindle Store' },
    { categoryId: 25, name: 'Luggage &amp; Travel Gear' },
    { categoryId: 26, name: 'Luxury Beauty' },
    { categoryId: 27, name: 'Movies &amp; TV' },
    { categoryId: 28, name: 'Music' },
    { categoryId: 29, name: 'Musical Instruments, Stage &amp; Studio' },
    { categoryId: 30, name: 'Office Products' },
    { categoryId: 31, name: 'Patio, Lawn &amp; Garden' },
    { categoryId: 32, name: 'Pet Supplies' },
    { categoryId: 33, name: 'Prime Video' },
    { categoryId: 34, name: 'Smart Home' },
    { categoryId: 35, name: 'Software' },
    { categoryId: 36, name: 'Sports &amp; Outdoors' },
    { categoryId: 37, name: 'Subscribe &amp; Save' },
    { categoryId: 38, name: 'Tools &amp; Home Improvement' },
    { categoryId: 39, name: 'Toys &amp; Games' },
    { categoryId: 40, name: 'Video Games' },
]